#!/usr/bin/env python

import argparse
import yaml
import os
import subprocess
import shutil

def install_from_spack(spec, env):
    # Delete ~/.intel
    intel_home = os.path.join(os.environ['HOME'], '.intel')
    if os.path.isdir(intel_home):
        shutil.rmtree(intel_home)
    # Delete ~/intel
    intel_home = os.path.join(os.environ['HOME'], 'intel')
    if os.path.isdir(intel_home):
        shutil.rmtree(intel_home)
    # Delete cached intel license
    intel_lic = os.path.join(env['spack_root'], 'etc', 'spack', 'licenses', 'intel', 'license.lic')
    if os.path.isfile(intel_lic):
        os.remove(intel_lic)
    # Install the spec package if absent
    if "No package" in subprocess.check_output("spack find {}".format(spec), shell=True).decode("utf-8"):
        print("{} not found. Build it.".format(spec))
        os.system("spack install {}".format(spec))

# Parse commandline options
parser = argparse.ArgumentParser(description='Deploy Spack software environment')

parser.add_argument('--env',
	type=argparse.FileType('r'),
	help='Environment file')
parser.add_argument('--install',
	action='store_true',
	help='Install packages')
parser.add_argument('--sync',
	action='store_true',
	help='Sync cached source files to the mirror site')

args = parser.parse_args()

# Read variables from configuration file, and 
# raise exception if $spack_root/bin/spack exists, and
# create $spack_conf directory if necessary.
env = yaml.load(args.env)

if not os.path.isfile(os.path.join(env['spack_root'], 'bin', 'spack')):
	raise FileNotFoundError(errno.ENOENT,
		os.strerror(errno.ENOENT),
		os.path.join(env['spack_root'], 'bin', 'spack'))

# Set and write to spack config file ~/.spack/config.yaml
if 'config' not in env.keys():
	env['config'] = {}
	env['config']['checksum'] = True
	env['config']['dirty'] = False
	env['config']['install_tree'] = os.path.join(env['spack_home'], 'opt', os.environ['PLATFORM'])
	env['config']['module_roots'] = {}
	env['config']['module_roots']['tcl'] = os.path.join(env['spack_home'], 'share', 'spack', 'modules', os.environ['PLATFORM'])
out = {}
out['config'] = env['config']
with open(os.path.join(env['spack_config'], 'config.yaml'), 'w') as outfile:
	yaml.dump(out, outfile, default_flow_style=False)

# Write $spack_config/modules.yaml
out = {}
out['modules'] = env['modules']
if out['modules'] is not None:
    with open(os.path.join(env['spack_config'], 'modules.yaml'), 'w') as outfile:
    	yaml.dump(out, outfile, default_flow_style=False)

# Write $spack_config/packages.yaml
out = {}
out['packages'] = env['packages']
if out['packages'] is not None:
    with open(os.path.join(env['spack_config'], 'packages.yaml'), 'w') as outfile:
    	yaml.dump(out, outfile, default_flow_style=False)

# Write $spack_config/compilers.yaml
out = {}
out['compilers'] = env['compilers']
with open(os.path.join(env['spack_config'], 'compilers.yaml'), 'w') as outfile:
	yaml.dump(out, outfile, default_flow_style=False)

# Write $spack_config/mirrors.yaml
out = {}
out['mirrors'] = env['mirrors']
with open(os.path.join(env['spack_config'], 'mirrors.yaml'), 'w') as outfile:
	yaml.dump(out, outfile, default_flow_style=False)

# Print the messsage
print(env['msg'])

# Run Spack if --sync is NOT set
if args.sync:
	print("Sync cached source files to the mirror site")
        os.system("rsync -avr --progress %s/var/spack/cache/ root@lb://var/lib/www/spack.pi.sjtu.edu.cn/mirror/" % env['spack_root'])

# Install packages
if args.install:
 	for p in env['install']:
 		install_from_spack(p, env)

# Refresh TCL modulefiles
os.system("spack module tcl refresh --delete-tree -y")
